"""remake comments

Revision ID: 05b5e62a9d87
Revises: f3adf477949e
Create Date: 2023-07-09 11:08:31.580258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b5e62a9d87'
down_revision = 'f3adf477949e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
