"""chat and messages

Revision ID: 1ca510a05c9f
Revises: b4117a262e20
Create Date: 2023-07-19 16:19:09.003855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca510a05c9f'
down_revision = 'b4117a262e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_users',
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], )
    )
    op.add_column('messages', sa.Column('content', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'Users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_id')
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'content')
    op.drop_table('chat_users')
    # ### end Alembic commands ###
