"""auto imcrement in comments

Revision ID: 2518ecccedfb
Revises: 53c277ad195c
Create Date: 2023-06-02 22:55:18.577340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2518ecccedfb'
down_revision = '53c277ad195c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
