"""backpopulates user

Revision ID: 299cb09adc79
Revises: 714a2d2247f0
Create Date: 2023-07-09 10:11:17.010550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299cb09adc79'
down_revision = '714a2d2247f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
