"""user relationship with comment and profile photo default chnge

Revision ID: 714a2d2247f0
Revises: ba11cb11d6cd
Create Date: 2023-07-07 11:51:37.408190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714a2d2247f0'
down_revision = 'ba11cb11d6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
