"""mould according to register

Revision ID: 96d5c7b13af1
Revises: 2518ecccedfb
Create Date: 2023-06-18 12:34:10.962549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d5c7b13af1'
down_revision = '2518ecccedfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
