"""added relationship in Followers and some extra feilds in users table

Revision ID: 98202c804993
Revises: ac6c98981312
Create Date: 2023-05-27 12:08:53.594483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98202c804993'
down_revision = 'ac6c98981312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('full_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'full_name')
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###
