"""backpopulates user

Revision ID: a5132274203b
Revises: 299cb09adc79
Create Date: 2023-07-09 10:34:51.888825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5132274203b'
down_revision = '299cb09adc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
