"""Followers table

Revision ID: ac6c98981312
Revises: c8c876dbfa42
Create Date: 2023-05-26 22:34:56.301229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6c98981312'
down_revision = 'c8c876dbfa42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('following_id', sa.Integer(), nullable=False))
    op.add_column('followers', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'followers', 'Users', ['following_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'created_at')
    op.drop_column('followers', 'following_id')
    # ### end Alembic commands ###
