"""remake comments

Revision ID: b4117a262e20
Revises: 05b5e62a9d87
Create Date: 2023-07-09 11:08:58.137435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4117a262e20'
down_revision = '05b5e62a9d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
