"""mould according to register

Revision ID: ba11cb11d6cd
Revises: 96d5c7b13af1
Create Date: 2023-06-18 15:42:31.705769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba11cb11d6cd'
down_revision = '96d5c7b13af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
