"""added about, profile_pic and full name in user; removed content and added images array and added related text for every post. Fixed relationships

Revision ID: d989deedb028
Revises: 98202c804993
Create Date: 2023-05-27 17:39:59.356561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd989deedb028'
down_revision = '98202c804993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('about', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('profile_photo', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('related_text', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'images')
    op.drop_column('posts', 'related_text')
    op.drop_column('Users', 'profile_photo')
    op.drop_column('Users', 'about')
    # ### end Alembic commands ###
