"""user relationship

Revision ID: e49d90e01d5f
Revises: a5132274203b
Create Date: 2023-07-09 10:49:20.910153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49d90e01d5f'
down_revision = 'a5132274203b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
